# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: personal24
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: email-api
service: email-service

provider:
  name: aws
  runtime: python3.8
  region: us-east-1

functions:
  sendEmail:
    handler: handler.send_email
    events:
      - http:
          path: send-email
          method: post

plugins:
  - serverless-python-requirements

custom:
  pythonRequirements:
    dockerizePip: true

resources:
  Resources:
    EmailPermissions:
      Type: AWS::IAM::Role
      Properties:
        RoleName: EmailSendingRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service: lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: EmailSendingPolicy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: Allow
                  Action:
                    - ses:SendEmail
                    - ses:SendRawEmail
                  Resource: "*"
